name: CI/CD for Loan Approval Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Training Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure GCP Project and Region
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud config set run/region us-central1

    - name: Authenticate Service Account for gsutil
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Fetch Latest Dataset
      run: |
        mkdir -p data/raw
        gsutil -o "Credentials:gs_service_key_file=/tmp/key.json" cp gs://loanapprovalprediction/data/raw/LoanApprovalPrediction.csv data/raw/LoanApprovalPrediction.csv

    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }} .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy loan-approval-pipeline \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }} \
          --platform managed \
          --allow-unauthenticated
