name: CI/CD for Loan Approval Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Training Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install jq (JSON Validator)
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Authenticate Service Account for gsutil
      run: |
        # Write the service account key to a file
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/key-raw.json

        # Replace escaped newlines with actual newlines and validate the JSON
        sed 's/\\\\n/\\n/g' /tmp/key-raw.json | jq . > /tmp/key.json

        # Activate the service account
        gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Configure GCP Project and Region
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud config set run/region us-central1

    - name: Fetch Latest Dataset
      run: |
        mkdir -p data/raw
        gsutil -o "Credentials:gs_service_key_file=/tmp/key.json" cp gs://loanapprovalprediction/data/raw/LoanApprovalPrediction.csv data/raw/LoanApprovalPrediction.csv

    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }} .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy loan-approval-pipeline \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/loan-approval-repo/loan-approval-pipeline:${{ github.sha }} \
          --platform managed \
          --allow-unauthenticated